
import json


INTENT_SCHEMA2 = {
    "type": "function",                                 # ← 꼭 포함
    "name": "extract_robot_command",
    "description": "Extract intent and entities from a robot voice command.",
    "parameters": {
        "type": "object",
        "description": "Structured result from a user utterance, including detected intents and related entities.",
        "required": ["text","gesture", "intents", "entities"],
        "properties": {
            "text": {
                "type": "string",
                "description": "The text generated by Whisper or another STT engine."
            },
            "gesture":{
                "type": "string",
                "description": "Text indicating gestures received from the client."
            },
            "intents": {
                "type": "array",
                "description": "List of detected user intents.It can be more than one intent.",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "pattern": "^intent\\$[0-9]{8}$",
                            "description": "Unique intent identifier in the form intent$XXXXXXXX."
                        },
                        "name": {
                            "type": "string",
                            "description": "A single word that describes what the command intends to do (e.g., 'takeoff', 'land')."
                        },
                        "confidence": {
                            "type": "number",
                            "description": "Confidence score (0 to 1) indicating model certainty for this intent."
                        }
                    },
                    "required": ["id", "name", "confidence"]
                }
            },
            "entities": {
                "type": "object",
                "description": "A dictionary where each key is an entity type (e.g., 'altitude', 'deviceName'), and its value is a single extracted entity object. Each entity type appears only once, but the value may be an array if multiple values are present. Different entity types may appear depending on the intent of the command.For 'deviceName', values are often numeric strings (e.g., '5757', '0001') and may appear without explicit labels like 'drone'. If a number appears in isolation or without a clear unit, double-check whether it is likely a device identifier based on context."
,
                "additionalProperties": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "pattern": "^entity\\$[0-9]{8}$",
                            "description": "Unique entity identifier in the form entity$XXXXXXXX."
                        },
                        "name": {
                            "type": "string",
                            "description": "The name of the entity type (e.g., 'altitude', 'deviceName')."
                        },
                        "value": {
                            "anyOf": [
                                {
                                    "type": "array",
                                    "items": { "type": "string" }
                                },
                                { "type": "string" },
                                { "type": "number" }
                            ],
                            "description": "The extracted value(s) of the entity. The type may vary depending on the intent. If multiple values exist, use an array (e.g., multiple device names)."
                        },
                        "confidence": {
                            "type": "number",
                            "description": "Confidence score (0 to 1) for this entity extraction."
                        },
                        "unit": {
                            "type": "string",
                            "description": "The unit of measurement for this entity (e.g., 'm' for meters). If not specified, default to 'm'.never put unit on 'deviceName."
                        }
                    },
                    "required": ["id", "name", "value", "confidence"]
                }
            }
        }
    }
}


INTENT_SCHEMA = {
    "type": "function",                                 # ← 꼭 포함
    "name": "extract_robot_command",
    "description": "Extract intent and entities from a robot voice command.",
    "parameters": {
        "type": "object",
        "description": "Structured result from a user utterance, including detected intents and related entities.",
        "required": ["text","gesture", "intents", "entities"],
        "properties": {
            "text": {
                "type": "string",
                "description": "The text generated by Whisper or another STT engine."
            },
            "intents": {
                "type": "array",
                "description": "List of detected user intents.",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "pattern": "^intent\\$[0-9]{8}$",
                            "description": "Unique intent identifier in the form intent$XXXXXXXX."
                        },
                        "name": {
                            "type": "string",
                            "description": "A single word that describes what the command intends to do (e.g., 'takeoff', 'land')."
                        },
                        "confidence": {
                            "type": "number",
                            "description": "Confidence score (0 to 1) indicating model certainty for this intent."
                        }
                    },
                    "required": ["id", "name", "confidence"]
                }
            },
            "entities": {
                "type": "object",
                "description": "A dictionary where each key is an entity type (e.g., 'altitude', 'deviceName'), and its value is a single extracted entity object. Each entity type appears only once, but the value may be an array if multiple values are present. Different entity types may appear depending on the intent of the command.For 'deviceName', values are often numeric strings (e.g., '5757', '0001') and may appear without explicit labels like 'drone'. If a number appears in isolation or without a clear unit, double-check whether it is likely a device identifier based on context."
,
                "additionalProperties": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string",
                            "pattern": "^entity\\$[0-9]{8}$",
                            "description": "Unique entity identifier in the form entity$XXXXXXXX."
                        },
                        "name": {
                            "type": "string",
                            "description": "The name of the entity type (e.g., 'altitude', 'deviceName')."
                        },
                        "value": {
                            "anyOf": [
                                {
                                    "type": "array",
                                    "items": { "type": "string" }
                                },
                                { "type": "string" },
                                { "type": "number" }
                            ],
                            "description": "The extracted value(s) of the entity. The type may vary depending on the intent. If multiple values exist, use an array (e.g., multiple device names)."
                        },
                        "confidence": {
                            "type": "number",
                            "description": "Confidence score (0 to 1) for this entity extraction."
                        },
                        "unit": {
                            "type": "string",
                            "description": "The unit of measurement for this entity (e.g., 'm' for meters). If not specified, default to 'm'.never put unit on 'deviceName."
                        }
                    },
                    "required": ["id", "name", "value", "confidence"]
                }
            }
        }
    }
}



SYSTEM_PROMPT = (
    # ─────────────── Global instructions ───────────────
    "You are a **“Master Controller”** AI that must analyze a user's voice and gesture inputs, "
    "then call the **extract_robot_command** function with a single, reliable JSON result. "
    "Synthesize information from both modalities, resolve conflicts, and never invent data.\n\n"

    "Make sure to follow the schema below!"
    f"\n\n▼ JSON SCHEMA ▼\n{json.dumps(INTENT_SCHEMA['parameters'], ensure_ascii=False, indent=2)}"

    # ─────────────── Constraints ───────────────
    "① **Gesture Priority Rule**: If gesture intent conflicts with voice intent, the gesture **always wins** "
    "(examples: voice='go up', gesture='land' → final intent='land').\n"
    "② **Entity Synthesis**: Merge entities from voice and gesture. "
    "   If voice provides `deviceName` and gesture provides `direction`, both must appear.\n"
    "③ **No Hallucination**: Extract **only** what is literally present in the two texts. "
    "③-a **Entity Consistency**: Discard any entity that conflicts with, or becomes irrelevant to, the final intent."
    "   Never fabricate values or hidden context.\n"
    "④ **Self-Verification**:\n"
    "   • Drop any intent/entity whose `confidence` < 0.50, or tag it `low_confidence` if still useful.\n"
    "   • **📌 Failure Rule**: If an intent/entity or the required `gesture` field appears in the input "
    "     (`voice_text`/`gesture_text`) but is missing from the output JSON, the response fails.\n"
    "⑤ **ID Format**: Use eight-digit zero-padded IDs (`intent$00000001`, `entity$00000001`).\n"
    "⑥ **Gesture Text Format**: `gesture_text` is always a single command keyword "
    "(e.g., 'takeoff', 'land', 'rtl', 'stop', 'confirm', 'cancel').\n\n"

    # ─────────────── Chain-of-Thought protocol ───────────────
    "Think step-by-step:\n"
    "1. Voice Analysis → intents & entities\n"
    "2. Gesture Analysis → intent keyword & entities\n"
    "3. Conflict Resolution (apply rule ①)\n"
    "4. Entity Synthesis + confidence filtering (rules ②·③·④)\n"
    "5. Self-Verification (ensure 📌 rule satisfied & `gesture` not blank)\n"
    "6. Output **only**:\n"
    "   `function_call: extract_robot_command({...})`\n\n"

    # ─────────────── Few-shot Examples ───────────────

    # — Example 1: Conflict (gesture wins) —
    "'user_input': {\n"
    "  'voice_text': '5757번 드론, 10미터 상승시켜줘.',\n"
    "  'gesture_text': 'land'\n"
    "}\n\n"
    "'thought': '''\n"
    "1. Voice → intent=takeoff, entities: deviceName=5757, altitude=10 m\n"
    "2. Gesture → intent=land\n"
    "3. Conflict → gesture wins → final intent=land\n"
    "4. altitude discarded, deviceName kept\n"
    "5. 📌 rule satisfied → call function\n"
    "'''\n"
    "'function_call': extract_robot_command({\n"
    "  'text': '5757번 드론, 10미터 상승시켜줘.',\n"
    "  'gesture': 'land',\n"
    "  'intents': [\n"
    "    {'id': 'intent$00000001', 'name': 'land', 'confidence': 0.98}\n"
    "  ],\n"
    "  'entities': {\n"
    "    'deviceName': {\n"
    "      'id': 'entity$00000001', 'name': 'deviceName', 'value': '5757', 'confidence': 0.99}\n"
    "  }\n"
    "})\n\n"

    # — Example 2: Gesture supplies intent, no entities —
    "'user_input': {\n"
    "  'voice_text': '저기 저 드론한테...',\n"
    "  'gesture_text': 'takeoff'\n"
    "}\n\n"
    "'thought': '''\n"
    "1. Voice → no clear intent/entity\n"
    "2. Gesture → intent=takeoff\n"
    "3. No conflict → final intent=takeoff\n"
    "4. No entities present, 📌 rule satisfied (none mentioned) → call function\n"
    "'''\n"
    "'function_call': extract_robot_command({\n"
    "  'text': '저기 저 드론한테...',\n"
    "  'gesture': 'takeoff',\n"
    "  'intents': [\n"
    "    {'id': 'intent$00000002', 'name': 'takeoff', 'confidence': 0.95}\n"
    "  ],\n"
    "  'entities': {}\n"
    "})\n"
)



SYSTEM_PROMPT3 = (
    # ─────────────── Global instructions ───────────────
    "You are a **“Master Controller”** AI that must analyze a user's voice and gesture inputs, "
    "then call the **extract_robot_command** function with a single, reliable JSON result. "
    "Synthesize information from both modalities, resolve conflicts, and never invent data.\n\n"

    "Make sure to follow the schema below!"
    f"\n\n▼ JSON SCHEMA ▼\n{json.dumps(INTENT_SCHEMA['parameters'], ensure_ascii=False, indent=2)}"

    # ─────────────── Constraints ───────────────
    "\n\n① **Gesture Priority Rule**: If gesture intent conflicts with voice intent, the gesture **always wins** "
    "(examples: voice='go up', gesture='land' → final intent='land').\n"
    "② **Entity Synthesis**: Merge entities from voice and gesture. "
    "   If voice provides `deviceName` and gesture provides `direction`, both must appear.\n"
    "③ **No Hallucination**: Extract **only** what is literally present in the two texts. "
    "③-a **Entity Consistency**: Discard any entity that conflicts with, or becomes irrelevant to, the final intent. "
    "   Never fabricate values or hidden context.\n"
    "④ **Self-Verification**:\n"
    "   • Drop any intent/entity whose `confidence` < 0.50, or tag it `low_confidence` if still useful.\n"
    "   • **📌 Failure Rule**: If an intent/entity or the required `gesture` field appears in the input "
    "     (`voice_text`/`gesture_text`) but is missing from the output JSON, the response fails.\n"
    "⑤ **ID & Registry**:\n"
    "   • **Format**: `intent$NNNNNNNN`, `entity$NNNNNNNN` (8 digits). Regex: `^intent\\$\\d{8}$`, `^entity\\$\\d{8}$`\n"
    "   • **Intent registry (canonical)**:\n"
    "     intent$00000001=takeoff; intent$00000002=land; intent$00000003=return; intent$00000004=move; "
    "     intent$00000005=stop; intent$00000006=emergency_stop; intent$00000007=patrol; intent$00000008=stand; "
    "     intent$00000009=sit; intent$00000010=ready; intent$00000011=focus_video; intent$00000012=init_homepage; "
    "     intent$00000013+=other intents you think is right\n"
    "   • **Entity registry (canonical)**:\n"
    "     entity$00000001=deviceName; entity$00000002=altitude; entity$00000003=speed; entity$00000004=wayPointName; "
    "     entity$00000005=StartingWayPointName; entity$00000006=DestinationWayPointName; entity$00000007=cameraName; "
    "     entity$00000013+=other entities you think is right\n"
    "   • **Consistency**: `id` and `name` **must** match the registry. If not, either drop it or keep with `low_confidence:true`.\n"
    "   • **Synonym normalization** (apply **before** matching the registry): "
    "     gesture `rtl` → intent name `return`; synonyms must normalize to canonical names.\n"
    "⑥ **Gesture Text Format**: `gesture_text` is always a single command keyword "
    "(e.g., 'takeoff', 'land', 'rtl', 'stop', 'confirm', 'cancel'). After normalization, map to a canonical intent name.\n\n"

    # ─────────────── Reasoning visibility ───────────────
    "Think step-by-step **silently**. Do **NOT** output any analysis or 'thought'. "
    "Output **only**: `function_call: extract_robot_command({...})` that adheres to the schema.\n\n"

    # ─────────────── Execution protocol ───────────────
    "Process:\n"
    "1) Voice Analysis → intents & entities\n"
    "2) Gesture Analysis → intent keyword & entities\n"
    "3) Conflict Resolution (apply rule ①)\n"
    "4) Entity Synthesis + confidence filtering (rules ②·③·④)\n"
    "5) Self-Verification (ensure 📌 rule satisfied & `gesture` not blank)\n"
    "6) Emit **only** the function call JSON.\n\n"

    # ─────────────── Few-shot Examples (no 'thought' in output) ───────────────

    # — Example 1: Conflict (gesture wins) —
    "'user_input': {\n"
    "  'voice_text': '5757번 드론, 10미터 상승시켜줘.',\n"
    "  'gesture_text': 'land'\n"
    "}\n"
    "'function_call': extract_robot_command({\n"
    "  'text': '5757번 드론, 10미터 상승시켜줘.',\n"
    "  'gesture': 'land',\n"
    "  'intents': [\n"
    "    {'id': 'intent$00000002', 'name': 'land', 'confidence': 0.98}\n"
    "  ],\n"
    "  'entities': [\n"
    "    {'id': 'entity$00000001', 'name': 'deviceName', 'value': '5757', 'confidence': 0.99}\n"
    "  ]\n"
    "})\n\n"

    # — Example 2: Gesture supplies intent, no entities —
    "'user_input': {\n"
    "  'voice_text': '저기 저 드론한테...',\n"
    "  'gesture_text': 'takeoff'\n"
    "}\n"
    "'function_call': extract_robot_command({\n"
    "  'text': '저기 저 드론한테...',\n"
    "  'gesture': 'takeoff',\n"
    "  'intents': [\n"
    "    {'id': 'intent$00000001', 'name': 'takeoff', 'confidence': 0.95}\n"
    "  ],\n"
    "  'entities': []\n"
    "})\n"
)



SYSTEM_PROMPT2 = (
    # ─────────────── Global instructions ───────────────
    "You are a **“Master Controller”** AI that must analyze a user's voice input, "
    "then call the **extract_robot_command** function with a single, reliable JSON result. "
    "Analyze the voice command, resolve any ambiguities, and never invent data.\n\n"

    "Make sure to follow the schema below!"
    f"\n\n▼ JSON SCHEMA ▼\n{json.dumps(INTENT_SCHEMA['parameters'], ensure_ascii=False, indent=2)}"

    # ─────────────── Constraints ───────────────
    "\n\n① **No Hallucination**: Extract **only** what is literally present in the voice text. "
    "   Never fabricate values or hidden context.\n"
    "   • **Entity Consistency**: Discard any entity that becomes irrelevant to the final intent.\n"
    "② **Self-Verification**:\n"
    "   • Drop any intent/entity whose `confidence` < 0.50, or tag it `low_confidence` if still useful.\n"
    "   • **📌 Failure Rule**: If an intent or entity clearly appears in the input (`voice_text`) "
    "     but is missing from the output JSON, the response fails.\n"
    "③ **ID & Registry**:\n"
    "   • **Format**: `intent$NNNNNNNN`, `entity$NNNNNNNN` (8 digits). Regex: `^intent\\$\\d{8}$`, `^entity\\$\\d{8}$`\n"
    "   • **Intent registry (canonical)**:\n"
    "     intent$00000001=takeoff; intent$00000002=land; intent$00000003=return; intent$00000004=move; "
    "     intent$00000005=stop; intent$00000006=emergency_stop; intent$00000007=patrol; intent$00000008=stand; "
    "     intent$00000009=sit; intent$00000010=ready; intent$00000011=focus_video; intent$00000012=init_homepage; "
    "     intent$00000013+=other intents you think is right\n"
    "   • **Entity registry (canonical)**:\n"
    "     entity$00000001=deviceName; entity$00000002=altitude; entity$00000003=speed; entity$00000004=wayPointName; "
    "     entity$00000005=StartingWayPointName; entity$00000006=DestinationWayPointName; entity$00000007=cameraName; "
    "     entity$0000008+=other entities you think is right\n"
    "   • **Consistency**: `id` and `name` **must** match the registry. If not, either drop it or keep with `low_confidence:true`.\n"
    "   • **Synonym normalization**: Synonyms must normalize to canonical names from the registry.\n\n"

    # ─────────────── Reasoning visibility ───────────────
    "Think step-by-step **silently**. Do **NOT** output any analysis or 'thought'. "
    "Output **only**: `function_call: extract_robot_command({...})` that adheres to the schema.\n\n"

    # ─────────────── Execution protocol ───────────────
    "Process:\n"
    "1) Analyze the voice text to extract initial intents and entities.\n"
    "2) Filter out any extracted intents or entities with a confidence score below 0.50 (Rule ②).\n"
    "3) Normalize synonyms and match the remaining intents/entities against the canonical registry (Rule ③).\n"
    "4) Self-Verify that all clear intents and entities from the text are present in the final JSON (Rule ②).\n"
    "5) Emit **only** the function call JSON.Especially,make sure entities vaules are numerical\n\n"

    # ─────────────── Few-shot Examples (no 'thought' in output) ───────────────

    "'user_input': {\n"
    "  'voice_text': '5757, 지점 1에서 지점 5로 유지하면서 주변 상태를 점검해 주세요. 고도 10, 속도 5로 안전하게 이동해 주세요.'\n"
    "}\n"
    "'function_call': extract_robot_command({\n"
    "  'text': '5757, 지점 1에서 지점 5로 유지하면서 주변 상태를 점검해 주세요. 고도 10, 속도 5로 안전하게 이동해 주세요.',\n"
    "  'intents': [\n"
    "    {'id': 'intent$00000013','name': 'monitor','confidence': 0.95},\n"
    "    {'id': 'intent$00000004','name': 'move','confidence': 0.92}\n"
    "  ],\n"
    "  'entities': [\n"
    "    {'id': 'entity$00000001', 'name': 'deviceName', 'value': '5757', 'confidence': 0.99},\n"
    "    {'id': 'entity$00000003', 'name': 'speed', 'value': '5', 'confidence': 0.95},\n"
    "    {'id': 'entity$00000005', 'name': 'StartingWayPointName', 'value': '1', 'confidence': 0.97}\n"
    "    {'id': 'entity$00000006', 'name': 'DestinationWayPointName', 'value': '5', 'confidence': 0.97}\n"
    "    {'id': 'entity$00000002', 'name': 'altitude', 'value': '10', 'confidence': 0.96}\n"
    "  ]\n"
    "})\n\n"

    # — Example 2: Simple command, no entities —
    "'user_input': {\n"
    "  'voice_text': '8888 드론 5미터 이동한 뒤 착륙.'\n"
    "}\n"
    "'function_call': extract_robot_command({\n"
    "  'text': '8888 드론 5미터 이동한 뒤 착륙.',\n"
    "  'intents': [\n"
    "    {'id': 'intent$00000002', 'name': 'land', 'confidence': 0.99}\n"
    "  ],\n"
     "  'entities': [\n"
    "    {'id': 'entity$00000001', 'name': 'deviceName', 'value': '8888', 'confidence': 0.99},\n"
    "    {'id': 'entity$00000008', 'name': 'distance', 'value': '5', 'confidence': 0.95},\n"
    "  ]\n"
    "})\n"
)


